/**
 * UF.DataAccess.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class SuspendedItemViewModel {
  MatchedIds?: Array<SuspendedItemViewModel>;
  FullName?: string;
  StudentId?: string;
  BirthDate?: string;
  AddressLine1?: string;
  HobsonsContactId?: string;
  HobsonsRegistrationId?: string;
  WorkdayId?: string;
  /**
   * rel_no from relation_rec table
   */
  AccessPortalId?: string;
  /**
   * prim_id from relation_rec table
   */
  StudentUniqueId?: string;
  /**
   * sec_id from relation_rec table
   */
  ParentUniqueId?: string;
  Phone?: string;
  ApplicationEmail?: string;
  AddressState?: string;
  AddressCtry?: string;
  AddressZip?: string;
  AddressCity?: string;
  Program?: string;
  SubProgram?: string;
  PassportNumber?: string;
  PassportCountry?: string;
  IsValid?: boolean;
  HasTranslationError?: boolean;
  IsSupplementalApplication?: boolean;
}
