/**
 * UF.DataAccess.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { FrsAgreementResponse } from '../model/frsAgreementResponse';

import { Configuration } from '../configuration';

export interface FrsServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   *
   *
   * @param userId
   * @param session
   * @param year
   */
  frsGetApiFrs(
    userId: string,
    session: string,
    year: string,
    extraHttpRequestParams?: any
  ): Observable<FrsAgreementResponse>;

  /**
   *
   *
   * @param userId
   * @param session
   * @param year
   */
  frsGetFrsAgreement(
    userId: string,
    session: string,
    year: string,
    extraHttpRequestParams?: any
  ): Observable<FrsAgreementResponse>;
}
