/**
 * UF.DataAccess.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { FullSyncResponse } from '../model/fullSyncResponse';

import { Configuration } from '../configuration';

export interface JenzabarInt902ServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   *
   *
   */
  jenzabarInt902GetApiJenzabarInt902(extraHttpRequestParams?: any): Observable<FullSyncResponse>;

  /**
   *
   *
   */
  jenzabarInt902JenInt902Begin(extraHttpRequestParams?: any): Observable<FullSyncResponse>;
}
