/**
 * UF.DataAccess.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { FullSyncResponse } from '../model/fullSyncResponse';
import { LogDetailResponse } from '../model/logDetailResponse';
import { SuspendedItemResponse } from '../model/suspendedItemResponse';

import { Configuration } from '../configuration';

export interface WorkdayHcm007ServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   * Delete the suspended item using the passed in ID from the Suspended Items DB
   *
   * @param suspendedItemId Suspended Item IDs to delete
   */
  workdayHcm007DeleteSuspendedItem(
    suspendedItemId: string,
    extraHttpRequestParams?: any
  ): Observable<SuspendedItemResponse>;

  /**
   * Delete the suspended item using the passed in ID from the Suspended Items DB
   *
   * @param suspendedItems List of Suspended Item IDs to delete
   */
  workdayHcm007DeleteSuspendedSelected(
    suspendedItems: Array<string>,
    extraHttpRequestParams?: any
  ): Observable<SuspendedItemResponse>;

  /**
   * Retrieves items that were suspended during the import
   *
   */
  workdayHcm007GetSuspendedItems(extraHttpRequestParams?: any): Observable<SuspendedItemResponse>;

  /**
   * Displays the import log for the given date
   *
   * @param exportDate Date the export from Workday HCM.INT007 Data Radius and import into Jenzabar CX occured.
   */
  workdayHcm007GetSyncLog(exportDate: string, extraHttpRequestParams?: any): Observable<LogDetailResponse>;

  /**
   * Gets a distinct list of dates that can be used for import log information
   *
   */
  workdayHcm007GetSyncLogDates(extraHttpRequestParams?: any): Observable<LogDetailResponse>;

  /**
   * Displays the import translation errors log for the given date
   *
   * @param exportDate Date the export from Workday HCM.INT004 Demographics Data Radius and import into Jenzabar CX occured.
   */
  workdayHcm007GetSyncTranslationLog(exportDate: string, extraHttpRequestParams?: any): Observable<LogDetailResponse>;

  /**
   * Initiates the creation of the Workstudy Award data CSV file for the HCM.INT007 integration
   *
   */
  workdayHcm007HcmInt007Begin(extraHttpRequestParams?: any): Observable<FullSyncResponse>;
}
