/**
 * UF.DataAccess.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AppStatus } from './appStatus';
import { Housing } from './housing';
import { Dining } from './dining';

export class AdirondackVerifyResponse {
  ErrorMessages?: Array<string>;
  HousingDiffs?: Array<Housing>;
  DiningDiffs?: Array<Dining>;
  AppStatusDiffs?: Array<AppStatus>;
  IsValid?: boolean;
  ErrorMessage?: string;
  ResultMessage?: string;
  ValidationErrors?: Array<string>;
}
