/**
 * UF.DataAccess.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class Csv004Model {
  WorkdayEmployeeId?: string;
  JenzabarId?: string;
  EmployeeType?: string;
  EmployeeTimeType?: string;
  EmployeeActiveFlag?: string;
  LastName?: string;
  Suffix?: string;
  MiddleName?: string;
  FirstName?: string;
  Email?: string;
  Cell?: string;
  Ssn?: string;
  Phone?: string;
  PhoneExt?: string;
  BirthDate?: string;
  Sex?: string;
  AddressCity?: string;
  AddressCtry?: string;
  AddressPostalCode?: string;
  AddressState?: string;
  AddressStreet?: string;
  AddressStreet2?: string;
  AddressStreet3?: string;
  Username?: string;
  Workphone?: string;
}
