/**
 * UF.DataAccess.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class Csv028Model {
  WorkdayEmployeeId?: string;
  JenzabarId?: string;
  Status?: string;
  DateRescinded?: string;
  BusinessProcessTransaction?: string;
  LastName?: string;
  FirstName?: string;
  WorkerStatus?: string;
  MiddleName?: string;
  Username?: string;
}
