/**
 * UF.DataAccess.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class CsvItemApplication {
  HobsonsContactId?: string;
  HobsonsStudentId?: string;
  Email?: string;
  RecordOwner?: string;
  AltLastName?: string;
  CcpCampusChoice?: string;
  CitzenshipCtry?: string;
  CitzenshipStatus?: string;
  ContactCity?: string;
  ContactCtry?: string;
  ContactPostalCode?: string;
  ContactState?: string;
  ContactStreet?: string;
  ContactStreet2?: string;
  ContactStreet3?: string;
  CountryOfBirth?: string;
  Birthdate?: string;
  EducationLevel?: string;
  Encrypted?: string;
  Ethnicity?: string;
  FirstName?: string;
  ForeignProvince?: string;
  Gender?: string;
  LastName?: string;
  MiddleName?: string;
  MilitaryBranch?: string;
  Mobile?: string;
  OhioCounty?: string;
  OrientationSession?: string;
  OtherCity?: string;
  OtherCtry?: string;
  OtherEmail?: string;
  OtherForeignProvince?: string;
  OtherMobile?: string;
  OtherPhone?: string;
  OtherPostalCode?: string;
  OtherState?: string;
  OtherStreet?: string;
  OtherStreet2?: string;
  ParentOrLegalGuardian2EmailAddress?: string;
  ParentOrLegalGuardian2Employer?: string;
  ParentOrLegalGuardian2FirstName?: string;
  ParentOrLegalGuardian2LastName?: string;
  ParentOrLegalGuardian2Occupation?: string;
  ParentOrLegalGuardianOccupation?: string;
  ParentOrLegalGuardianEmailAddress?: string;
  ParentOrLegalGuardianEmployer?: string;
  ParentOrLegalGuardianFirstName?: string;
  ParentOrLegalGuardianLastName?: string;
  ParentOrLegalGuardianPhone?: string;
  ParentOrLegalGuardian2Phone?: string;
  ParentOrLegalGuardian2Relationship?: string;
  ParentOrLegalGuardian1Relationship?: string;
  Phone?: string;
  PreferredName?: string;
  Prefix?: string;
  PreviouslyApplied2?: string;
  Race?: string;
  RadiusLeadSource?: string;
  ReligiousAffliation?: string;
  Salutation?: string;
  Suffix?: string;
  RegistrationId?: string;
  AcademicConcentration?: string;
  AcademicLevel?: string;
  FullTimePartTime?: string;
  AdmitType?: string;
  EntryTerm?: string;
  DisabilitySelection?: string;
  FinancialAid?: string;
  EducatorEndorsements?: string;
  EducatorLicenses?: string;
  PrevAppliedProgOfInterest?: string;
  ProgOfInterestGrad?: string;
  ProgOfInterestUndg?: string;
  Housing?: string;
  TransferCumGpa?: string;
  TotalHoursEarned?: string;
  TransferCumTransType?: string;
  TransferCumLastAttendDate?: string;
  ReEntry?: string;
  RegCutoffDate?: string;
  PassportNumber?: string;
  PassportCountry?: string;
  ApplicationStatus?: string;
  IsASupplementalApplication?: string;
  PipelineSchool?: string;
  PipelineSchoolId?: string;
}
