/**
 * UF.DataAccess.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class FrsAgreement {
  StudentId?: string;
  Fullname?: string;
  AddressLine1?: string;
  AddressLine2?: string;
  City?: string;
  State?: string;
  Zip?: string;
  Ssn?: string;
  Phone?: string;
  NtLogin?: string;
  EbillSignDate?: string;
  EbillInputName?: string;
  EbillVersion?: string;
  Session?: string;
  Year?: string;
  Content?: string;
  IsValid?: boolean;
  ErrorMessage?: string;
}
