/**
 * UF.DataAccess.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class Housing {
  StudentNumber?: string;
  CarsBldg?: string;
  ThdBldg?: string;
  CarsRoom?: string;
  ThdRoom?: string;
  CarsResidentAssistant?: string;
  ThdResidentAssistant?: string;
}
