/**
 * UF.DataAccess.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class IStudentEligibility {
  CXId?: string;
  WorkdayId?: string;
  LastName?: string;
  FirstName?: string;
  Program?: string;
  Class?: string;
  ACST?: string;
  RegisteredHours?: string;
  InternationalStudent?: string;
  VisaCode?: string;
  EligibilityEndDate?: string;
  EligibilityStatus?: string;
  InEligibilityReasons?: string;
}
