/**
 * UF.DataAccess.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Credential } from './credential';

export class Person {
  NTLogin?: string;
  FirstName?: string;
  MiddleName?: string;
  LastName?: string;
  ImageSrc?: string;
  Title?: string;
  Phone?: string;
  Location?: string;
  Email?: string;
  Profile?: string;
  Activities?: string;
  Publications?: string;
  Performances?: string;
  YearStarted?: string;
  GuidID?: string;
  Departments?: Array<string>;
  TerminalDegrees?: Array<string>;
  Credentials?: Array<Credential>;
}
