/**
 * UF.DataAccess.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams, HttpResponse, HttpEvent, HttpParameterCodec } from '@angular/common/http';
import { CustomHttpParameterCodec } from '../encoder';
import { Observable } from 'rxjs';

import { ContactResponse } from '../model/contactResponse';
import { FullSyncResponse } from '../model/fullSyncResponse';
import { LogDetailResponse } from '../model/logDetailResponse';
import { SuspendedItemResponse } from '../model/suspendedItemResponse';

import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';
import { AccessPortalServiceInterface } from './accessPortal.serviceInterface';

@Injectable()
export class AccessPortalService implements AccessPortalServiceInterface {
  protected basePath = 'http://localhost:8080';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();
  public encoder: HttpParameterCodec;

  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string,
    @Optional() configuration: Configuration
  ) {
    if (configuration) {
      this.configuration = configuration;
      this.configuration.basePath = configuration.basePath || basePath || this.basePath;
    } else {
      this.configuration.basePath = basePath || this.basePath;
    }
    this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
  }

  /**
   * Delete the suspended item using the passed in ID from the Suspended Items DB
   * @param suspendedItemId Suspended Item IDs to delete
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public accessPortalDeleteSuspendedItem(
    suspendedItemId: string,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<SuspendedItemResponse>;
  public accessPortalDeleteSuspendedItem(
    suspendedItemId: string,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<SuspendedItemResponse>>;
  public accessPortalDeleteSuspendedItem(
    suspendedItemId: string,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<SuspendedItemResponse>>;
  public accessPortalDeleteSuspendedItem(
    suspendedItemId: string,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (suspendedItemId === null || suspendedItemId === undefined) {
      throw new Error(
        'Required parameter suspendedItemId was null or undefined when calling accessPortalDeleteSuspendedItem.'
      );
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['application/json', 'text/json', 'application/xml', 'text/xml'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json',
      'text/json',
      'application/xml',
      'text/xml',
      'application/x-www-form-urlencoded'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.post<SuspendedItemResponse>(
      `${this.configuration.basePath}/api/AccessPortal/DeleteSuspendedItem`,
      suspendedItemId,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Displays the import log for the given date
   * @param exportDate Date the export from AccessPortal and import into Jenzabar CX occured.
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public accessPortalGetApiAccessPortal(
    exportDate: string,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<LogDetailResponse>;
  public accessPortalGetApiAccessPortal(
    exportDate: string,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<LogDetailResponse>>;
  public accessPortalGetApiAccessPortal(
    exportDate: string,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<LogDetailResponse>>;
  public accessPortalGetApiAccessPortal(
    exportDate: string,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (exportDate === null || exportDate === undefined) {
      throw new Error(
        'Required parameter exportDate was null or undefined when calling accessPortalGetApiAccessPortal.'
      );
    }

    let queryParameters = new HttpParams({ encoder: this.encoder });
    if (exportDate !== undefined && exportDate !== null) {
      queryParameters = queryParameters.set('exportDate', <any>exportDate);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['application/json', 'text/json', 'application/xml', 'text/xml'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    return this.httpClient.get<LogDetailResponse>(`${this.configuration.basePath}/api/AccessPortal`, {
      params: queryParameters,
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress
    });
  }

  /**
   * Retrieves details regarding the employees
   * @param contactId Cx ID of the contact to retrieve information for
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public accessPortalGetContactDetail(
    contactId: string,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<ContactResponse>;
  public accessPortalGetContactDetail(
    contactId: string,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<ContactResponse>>;
  public accessPortalGetContactDetail(
    contactId: string,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<ContactResponse>>;
  public accessPortalGetContactDetail(
    contactId: string,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (contactId === null || contactId === undefined) {
      throw new Error('Required parameter contactId was null or undefined when calling accessPortalGetContactDetail.');
    }

    let queryParameters = new HttpParams({ encoder: this.encoder });
    if (contactId !== undefined && contactId !== null) {
      queryParameters = queryParameters.set('contactId', <any>contactId);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['application/json', 'text/json', 'application/xml', 'text/xml'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    return this.httpClient.get<ContactResponse>(`${this.configuration.basePath}/api/AccessPortal/GetContactDetail`, {
      params: queryParameters,
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress
    });
  }

  /**
   * Initiates an import of AccessPortal data into Jenzabar CX
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public accessPortalGetFullSync(observe?: 'body', reportProgress?: boolean): Observable<FullSyncResponse>;
  public accessPortalGetFullSync(
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<FullSyncResponse>>;
  public accessPortalGetFullSync(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<FullSyncResponse>>;
  public accessPortalGetFullSync(observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    let headers = this.defaultHeaders;

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['application/json', 'text/json', 'application/xml', 'text/xml'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    return this.httpClient.get<FullSyncResponse>(`${this.configuration.basePath}/api/AccessPortal/GetFullSync`, {
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress
    });
  }

  /**
   * Retrieves items that were suspended during the import
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public accessPortalGetSuspendedItems(observe?: 'body', reportProgress?: boolean): Observable<SuspendedItemResponse>;
  public accessPortalGetSuspendedItems(
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<SuspendedItemResponse>>;
  public accessPortalGetSuspendedItems(
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<SuspendedItemResponse>>;
  public accessPortalGetSuspendedItems(observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    let headers = this.defaultHeaders;

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['application/json', 'text/json', 'application/xml', 'text/xml'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    return this.httpClient.get<SuspendedItemResponse>(
      `${this.configuration.basePath}/api/AccessPortal/GetSuspendedItems`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Displays the import log for the given date
   * @param exportDate Date the export from AccessPortal and import into Jenzabar CX occured.
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public accessPortalGetSyncLog(
    exportDate: string,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<LogDetailResponse>;
  public accessPortalGetSyncLog(
    exportDate: string,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<LogDetailResponse>>;
  public accessPortalGetSyncLog(
    exportDate: string,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<LogDetailResponse>>;
  public accessPortalGetSyncLog(
    exportDate: string,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (exportDate === null || exportDate === undefined) {
      throw new Error('Required parameter exportDate was null or undefined when calling accessPortalGetSyncLog.');
    }

    let queryParameters = new HttpParams({ encoder: this.encoder });
    if (exportDate !== undefined && exportDate !== null) {
      queryParameters = queryParameters.set('exportDate', <any>exportDate);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['application/json', 'text/json', 'application/xml', 'text/xml'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    return this.httpClient.get<LogDetailResponse>(`${this.configuration.basePath}/api/AccessPortal/GetSyncLog`, {
      params: queryParameters,
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress
    });
  }

  /**
   * Gets a distinct list of dates that can be used for import log information
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public accessPortalGetSyncLogDates(observe?: 'body', reportProgress?: boolean): Observable<LogDetailResponse>;
  public accessPortalGetSyncLogDates(
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<LogDetailResponse>>;
  public accessPortalGetSyncLogDates(
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<LogDetailResponse>>;
  public accessPortalGetSyncLogDates(observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    let headers = this.defaultHeaders;

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['application/json', 'text/json', 'application/xml', 'text/xml'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    return this.httpClient.get<LogDetailResponse>(`${this.configuration.basePath}/api/AccessPortal/GetSyncLogDates`, {
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress
    });
  }

  /**
   * User clicks \&quot;Create\&quot; in UI.  Retrieves the suspended item using the passed in ID from the Suspended Items DB and creates new records the Jenzabar CX database
   * @param suspendedItemId ID of the suspended item to process as a new item in Jenzabar CX
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public accessPortalPostSuspendedItem(
    suspendedItemId: string,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<SuspendedItemResponse>;
  public accessPortalPostSuspendedItem(
    suspendedItemId: string,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<SuspendedItemResponse>>;
  public accessPortalPostSuspendedItem(
    suspendedItemId: string,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<SuspendedItemResponse>>;
  public accessPortalPostSuspendedItem(
    suspendedItemId: string,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (suspendedItemId === null || suspendedItemId === undefined) {
      throw new Error(
        'Required parameter suspendedItemId was null or undefined when calling accessPortalPostSuspendedItem.'
      );
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['application/json', 'text/json', 'application/xml', 'text/xml'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json',
      'text/json',
      'application/xml',
      'text/xml',
      'application/x-www-form-urlencoded'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.post<SuspendedItemResponse>(
      `${this.configuration.basePath}/api/AccessPortal/PostSuspendedItem`,
      suspendedItemId,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * User clicks \&quot;Match\&quot; in UI. Retrieves the suspended item using the passed in ID from the Suspended Items DB and creates the new adm record and updates the remaining records in the Jenzabar CX database
   * @param suspendedItemId ID of the suspended item to process as an update in Jenzabar CX
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public accessPortalPutSuspendedItem(
    suspendedItemId: string,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<SuspendedItemResponse>;
  public accessPortalPutSuspendedItem(
    suspendedItemId: string,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<SuspendedItemResponse>>;
  public accessPortalPutSuspendedItem(
    suspendedItemId: string,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<SuspendedItemResponse>>;
  public accessPortalPutSuspendedItem(
    suspendedItemId: string,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (suspendedItemId === null || suspendedItemId === undefined) {
      throw new Error(
        'Required parameter suspendedItemId was null or undefined when calling accessPortalPutSuspendedItem.'
      );
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['application/json', 'text/json', 'application/xml', 'text/xml'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json',
      'text/json',
      'application/xml',
      'text/xml',
      'application/x-www-form-urlencoded'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.post<SuspendedItemResponse>(
      `${this.configuration.basePath}/api/AccessPortal/PutSuspendedItem`,
      suspendedItemId,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }
}
