/**
 * UF.DataAccess.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { AdirondackResponse } from '../model/adirondackResponse';
import { AdirondackVerifyResponse } from '../model/adirondackVerifyResponse';
import { LogDetailResponse } from '../model/logDetailResponse';

import { Configuration } from '../configuration';

export interface AdirondackServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   *
   *
   */
  adirondackAdirondackBegin(extraHttpRequestParams?: any): Observable<AdirondackResponse>;

  /**
   * Displays the import log for the given date
   *
   * @param exportDate Date the export from CX to Adirondack occured.
   */
  adirondackGetApiAdirondack(exportDate: string, extraHttpRequestParams?: any): Observable<LogDetailResponse>;

  /**
   * Displays the import log for the given date
   *
   * @param exportDate Date the export from CX to Adirondack occured.
   */
  adirondackGetSyncLog(exportDate: string, extraHttpRequestParams?: any): Observable<LogDetailResponse>;

  /**
   * Gets a distinct list of dates that can be used for import log information
   *
   */
  adirondackGetSyncLogDates(extraHttpRequestParams?: any): Observable<LogDetailResponse>;

  /**
   * the client uploads a CSV file created by Adirondack
   *
   * @param csvData
   */
  adirondackVerifyAppStatus(csvData: string, extraHttpRequestParams?: any): Observable<AdirondackVerifyResponse>;

  /**
   * The client uploads a CSV file created by Adironack.  The controller reads the file data and compares the housing and dining data  from the Adirondack data to CARS.    The housing and dining differences  are returned to the client to display in a grid.
   *
   * @param csvData
   */
  adirondackVerifyDining(csvData: string, extraHttpRequestParams?: any): Observable<AdirondackVerifyResponse>;

  /**
   * The client uploads a CSV file created by Adironack.  The controller reads the file data and compares the housing and dining data  from the Adirondack data to CARS.    The housing and dining differences  are returned to the client to display in a grid.
   *
   * @param csvData
   */
  adirondackVerifyHousing(csvData: string, extraHttpRequestParams?: any): Observable<AdirondackVerifyResponse>;
}
