/**
 * UF.DataAccess.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { Configuration } from '../configuration';

export interface EmployeeServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   * Retrieves campus information for the logged in user, such as, office number, dorm, phone, email, etc.
   *
   */
  employeeGet(extraHttpRequestParams?: any): Observable<object>;

  /**
   * Retrieves campus information for the logged in user, such as, office number, dorm, phone, email, etc.
   *
   */
  employeeGetApiEmployee(extraHttpRequestParams?: any): Observable<object>;
}
