/**
 * UF.DataAccess.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { FullSyncResponse } from '../model/fullSyncResponse';
import { LogDetailResponse } from '../model/logDetailResponse';
import { SuspendedItemResponse } from '../model/suspendedItemResponse';

import { Configuration } from '../configuration';

export interface JenzabarInt902ServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   * Delete the suspended item using the passed in ID from the Suspended Items DB
   *
   * @param suspendedItemId Suspended Item IDs to delete
   */
  jenzabarInt902DeleteSuspendedItem(
    suspendedItemId: string,
    extraHttpRequestParams?: any
  ): Observable<SuspendedItemResponse>;

  /**
   * Delete the suspended item using the passed in ID from the Suspended Items DB
   *
   * @param suspendedItems List of Suspended Item IDs to delete
   */
  jenzabarInt902DeleteSuspendedSelected(
    suspendedItems: Array<string>,
    extraHttpRequestParams?: any
  ): Observable<SuspendedItemResponse>;

  /**
   * Displays the import log for the given date
   *
   * @param exportDate Date the JEN.Int902 import into Jenzabar occured
   */
  jenzabarInt902GetApiJenzabarInt902(exportDate: string, extraHttpRequestParams?: any): Observable<LogDetailResponse>;

  /**
   * Retrieves items that were suspended during the import
   *
   */
  jenzabarInt902GetSuspendedItems(extraHttpRequestParams?: any): Observable<SuspendedItemResponse>;

  /**
   * Displays the import log for the given date
   *
   * @param exportDate Date the JEN.Int902 import into Jenzabar occured
   */
  jenzabarInt902GetSyncLog(exportDate: string, extraHttpRequestParams?: any): Observable<LogDetailResponse>;

  /**
   * Gets a distinct list of dates that can be used for import log information
   *
   */
  jenzabarInt902GetSyncLogDates(extraHttpRequestParams?: any): Observable<LogDetailResponse>;

  /**
   *
   *
   */
  jenzabarInt902JenInt902Begin(extraHttpRequestParams?: any): Observable<FullSyncResponse>;
}
