/**
 * UF.DataAccess.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { LogEntryDetailResponse } from '../model/logEntryDetailResponse';

import { Configuration } from '../configuration';

export interface LogEntryDetailServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   * Gets log data for specified Id
   *
   * @param id1
   * @param id2
   * @param logType
   */
  logEntryDetailGetApiLogEntryDetail(
    id1: string,
    id2: string,
    logType: string,
    extraHttpRequestParams?: any
  ): Observable<LogEntryDetailResponse>;

  /**
   * Gets log data for specified Id
   *
   * @param id1
   * @param id2
   * @param logType
   */
  logEntryDetailGetLogEntryDetails(
    id1: string,
    id2: string,
    logType: string,
    extraHttpRequestParams?: any
  ): Observable<LogEntryDetailResponse>;

  /**
   * Test email notification
   *
   */
  logEntryDetailTestEmailNotification(extraHttpRequestParams?: any): Observable<LogEntryDetailResponse>;
}
