/**
 * UF.DataAccess.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { Configuration } from '../configuration';

export interface PersonalServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   * Retrieves information needed to populate the Personal Information view in the MyProfile application.  Can also be used when personal information such as addresses, personal contact and emergency contacts information is needed.
   *
   */
  personalGet(extraHttpRequestParams?: any): Observable<object>;

  /**
   * Retrieves information needed to populate the Personal Information view in the MyProfile application.  Can also be used when personal information such as addresses, personal contact and emergency contacts information is needed.
   *
   */
  personalGetApiPersonal(extraHttpRequestParams?: any): Observable<object>;
}
