/**
 * UF.DataAccess.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { Configuration } from '../configuration';

export interface RoleServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   * Retrieves the role data used for the logged in user.
   *
   */
  roleGet(extraHttpRequestParams?: any): Observable<object>;

  /**
   * Retrieves the role data used for the logged in user.
   *
   */
  roleGetApiRole(extraHttpRequestParams?: any): Observable<object>;
}
