/**
 * UF.DataAccess.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams, HttpResponse, HttpEvent, HttpParameterCodec } from '@angular/common/http';
import { CustomHttpParameterCodec } from '../encoder';
import { Observable } from 'rxjs';

import { UFAuthorizationResponse } from '../model/uFAuthorizationResponse';
import { UFUserRole } from '../model/uFUserRole';

import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';
import { UFAuthorizationServiceInterface } from './uFAuthorization.serviceInterface';

@Injectable()
export class UFAuthorizationService implements UFAuthorizationServiceInterface {
  protected basePath = 'http://localhost:8080';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();
  public encoder: HttpParameterCodec;

  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string,
    @Optional() configuration: Configuration
  ) {
    if (configuration) {
      this.configuration = configuration;
      this.configuration.basePath = configuration.basePath || basePath || this.basePath;
    } else {
      this.configuration.basePath = basePath || this.basePath;
    }
    this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
  }

  /**
   * @param ufUserRole
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public uFAuthorizationCreateUserRole(
    ufUserRole: UFUserRole,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<UFAuthorizationResponse>;
  public uFAuthorizationCreateUserRole(
    ufUserRole: UFUserRole,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<UFAuthorizationResponse>>;
  public uFAuthorizationCreateUserRole(
    ufUserRole: UFUserRole,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<UFAuthorizationResponse>>;
  public uFAuthorizationCreateUserRole(
    ufUserRole: UFUserRole,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (ufUserRole === null || ufUserRole === undefined) {
      throw new Error(
        'Required parameter ufUserRole was null or undefined when calling uFAuthorizationCreateUserRole.'
      );
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['application/json', 'text/json', 'application/xml', 'text/xml'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json',
      'text/json',
      'application/xml',
      'text/xml',
      'application/x-www-form-urlencoded'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.post<UFAuthorizationResponse>(
      `${this.configuration.basePath}/api/UFAuthorization/CreateUserRole`,
      ufUserRole,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * @param ufUserRole
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public uFAuthorizationDeleteUserRole(
    ufUserRole: UFUserRole,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<UFAuthorizationResponse>;
  public uFAuthorizationDeleteUserRole(
    ufUserRole: UFUserRole,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<UFAuthorizationResponse>>;
  public uFAuthorizationDeleteUserRole(
    ufUserRole: UFUserRole,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<UFAuthorizationResponse>>;
  public uFAuthorizationDeleteUserRole(
    ufUserRole: UFUserRole,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (ufUserRole === null || ufUserRole === undefined) {
      throw new Error(
        'Required parameter ufUserRole was null or undefined when calling uFAuthorizationDeleteUserRole.'
      );
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['application/json', 'text/json', 'application/xml', 'text/xml'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json',
      'text/json',
      'application/xml',
      'text/xml',
      'application/x-www-form-urlencoded'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.post<UFAuthorizationResponse>(
      `${this.configuration.basePath}/api/UFAuthorization/DeleteUserRole`,
      ufUserRole,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public uFAuthorizationGetUserRoleIds(observe?: 'body', reportProgress?: boolean): Observable<UFAuthorizationResponse>;
  public uFAuthorizationGetUserRoleIds(
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<UFAuthorizationResponse>>;
  public uFAuthorizationGetUserRoleIds(
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<UFAuthorizationResponse>>;
  public uFAuthorizationGetUserRoleIds(observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    let headers = this.defaultHeaders;

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['application/json', 'text/json', 'application/xml', 'text/xml'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    return this.httpClient.get<UFAuthorizationResponse>(
      `${this.configuration.basePath}/api/UFAuthorization/GetUserRoleIds`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public uFAuthorizationGetUserRoles(observe?: 'body', reportProgress?: boolean): Observable<UFAuthorizationResponse>;
  public uFAuthorizationGetUserRoles(
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<UFAuthorizationResponse>>;
  public uFAuthorizationGetUserRoles(
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<UFAuthorizationResponse>>;
  public uFAuthorizationGetUserRoles(observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    let headers = this.defaultHeaders;

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['application/json', 'text/json', 'application/xml', 'text/xml'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    return this.httpClient.get<UFAuthorizationResponse>(
      `${this.configuration.basePath}/api/UFAuthorization/GetUserRoles`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public uFAuthorizationGetUserRolesScript(observe?: 'body', reportProgress?: boolean): Observable<object>;
  public uFAuthorizationGetUserRolesScript(
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<object>>;
  public uFAuthorizationGetUserRolesScript(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<object>>;
  public uFAuthorizationGetUserRolesScript(observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    let headers = this.defaultHeaders;

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['application/json', 'text/json', 'application/xml', 'text/xml'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    return this.httpClient.get<object>(`${this.configuration.basePath}/api/UFAuthorization/GetUserRolesScript`, {
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress
    });
  }
}
