/**
 * UF.DataAccess.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { FullSyncResponse } from '../model/fullSyncResponse';
import { LogDetailResponse } from '../model/logDetailResponse';
import { SuspendedItemResponse } from '../model/suspendedItemResponse';

import { Configuration } from '../configuration';

export interface WorkdayHcm028ServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   * Delete the suspended item using the passed in ID from the Suspended Items DB
   *
   * @param suspendedItemId Suspended Item IDs to delete
   */
  workdayHcm028DeleteSuspendedItem(
    suspendedItemId: string,
    extraHttpRequestParams?: any
  ): Observable<SuspendedItemResponse>;

  /**
   * Delete the suspended item using the passed in ID from the Suspended Items DB
   *
   * @param suspendedItems List of Suspended Item IDs to delete
   */
  workdayHcm028DeleteSuspendedSelected(
    suspendedItems: Array<string>,
    extraHttpRequestParams?: any
  ): Observable<SuspendedItemResponse>;

  /**
   * Displays the import log for the given date
   *
   * @param exportDate Date the export from Workday HCM.INT008 Data Radius and import into Jenzabar CX occured.
   */
  workdayHcm028GetApiWorkdayHcm028(exportDate: string, extraHttpRequestParams?: any): Observable<LogDetailResponse>;

  /**
   * Retrieves items that were suspended during the import
   *
   */
  workdayHcm028GetSuspendedItems(extraHttpRequestParams?: any): Observable<SuspendedItemResponse>;

  /**
   * Displays the import log for the given date
   *
   * @param exportDate Date the export from Workday HCM.INT008 Data Radius and import into Jenzabar CX occured.
   */
  workdayHcm028GetSyncLog(exportDate: string, extraHttpRequestParams?: any): Observable<LogDetailResponse>;

  /**
   * Gets a distinct list of dates that can be used for import log information
   *
   */
  workdayHcm028GetSyncLogDates(extraHttpRequestParams?: any): Observable<LogDetailResponse>;

  /**
   * Initiates the removal of rescinds from CX via a CSV file dropped by Workday for the HCM.INT028 integration
   *
   */
  workdayHcm028HcmInt028Begin(extraHttpRequestParams?: any): Observable<FullSyncResponse>;

  /**
   * Retrieves the suspended item using the passed in ID from the Suspended Items DB and creates the new adm record and updates the remaining records in the Jenzabar CX database
   *
   * @param suspendedItemId ID of the suspended item to process as an update in Jenzabar CX
   */
  workdayHcm028PutApiWorkdayHcm028(
    suspendedItemId: string,
    extraHttpRequestParams?: any
  ): Observable<SuspendedItemResponse>;

  /**
   * Retrieves the suspended item using the passed in ID from the Suspended Items DB and creates the new adm record and updates the remaining records in the Jenzabar CX database
   *
   * @param suspendedItemId ID of the suspended item to process as an update in Jenzabar CX
   */
  workdayHcm028PutSuspendedItem(
    suspendedItemId: string,
    extraHttpRequestParams?: any
  ): Observable<SuspendedItemResponse>;
}
