/**
 * UF.DataAccess.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { Csv004Model } from '../model/csv004Model';
import { FullSyncResponse } from '../model/fullSyncResponse';
import { LogDetailResponse } from '../model/logDetailResponse';
import { SuspendedItemResponse } from '../model/suspendedItemResponse';

import { Configuration } from '../configuration';

export interface WorkdayHcm004ServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   * Delete the suspended item using the passed in ID from the Suspended Items DB
   *
   * @param suspendedItemId Suspended Item IDs to delete
   */
  workdayHcm004DeleteSuspendedItem(
    suspendedItemId: string,
    extraHttpRequestParams?: any
  ): Observable<SuspendedItemResponse>;

  /**
   * Delete the suspended item using the passed in ID from the Suspended Items DB
   *
   * @param suspendedItems List of Suspended Item IDs to delete
   */
  workdayHcm004DeleteSuspendedSelected(
    suspendedItems: Array<string>,
    extraHttpRequestParams?: any
  ): Observable<SuspendedItemResponse>;

  /**
   * Retrieves items that were suspended during the import
   *
   */
  workdayHcm004GetSuspendedItems(extraHttpRequestParams?: any): Observable<SuspendedItemResponse>;

  /**
   * Displays the import log for the given date
   *
   * @param exportDate Date the export from Workday HCM.INT004 Demographics Data Radius and import into Jenzabar CX occured.
   */
  workdayHcm004GetSyncLog(exportDate: string, extraHttpRequestParams?: any): Observable<LogDetailResponse>;

  /**
   * Gets a distinct list of dates that can be used for import log information
   *
   */
  workdayHcm004GetSyncLogDates(extraHttpRequestParams?: any): Observable<LogDetailResponse>;

  /**
   * Displays the import translation errors log for the given date
   *
   * @param exportDate Date the export from Workday HCM.INT004 Demographics Data Radius and import into Jenzabar CX occured.
   */
  workdayHcm004GetSyncTranslationLog(exportDate: string, extraHttpRequestParams?: any): Observable<LogDetailResponse>;

  /**
   * Initiates an import of Workday data into Jenzabar CX
   *
   */
  workdayHcm004HcmInt004Begin(extraHttpRequestParams?: any): Observable<FullSyncResponse>;

  /**
   *
   *
   */
  workdayHcm004HcmInt004bBegin(extraHttpRequestParams?: any): Observable<FullSyncResponse>;

  /**
   * Start the import process the suspended item using the passed in ID from the Suspended Items DB and creates new records the Jenzabar CX database
   *
   * @param suspendedItemId ID of the suspended item to process as a new item in Jenzabar CX
   */
  workdayHcm004ImportSuspendedItem(
    suspendedItemId: string,
    extraHttpRequestParams?: any
  ): Observable<SuspendedItemResponse>;

  /**
   * Start the import process the suspended item using the passed in ID from the Suspended Items DB and creates new records the Jenzabar CX database
   *
   * @param suspendedItems List of Suspended Item IDs to process as a new item in Jenzabar CX
   */
  workdayHcm004ImportSuspendedSelected(
    suspendedItems: Array<string>,
    extraHttpRequestParams?: any
  ): Observable<SuspendedItemResponse>;

  /**
   * Processes the Workday HCM.INT004 Demographics Data Radius data and updates the Jenzabar CX database
   *
   * @param csv004Items Serialized Csv004 objects containing Workday data to import into Jenzabar CX
   */
  workdayHcm004Post(csv004Items: Array<Csv004Model>, extraHttpRequestParams?: any): Observable<object>;

  /**
   * Retrieves the suspended item using the passed in ID from the Suspended Items DB and creates new records the Jenzabar CX database
   *
   * @param suspendedItemId ID of the suspended item to process as a new item in Jenzabar CX
   */
  workdayHcm004PostSuspendedItem(
    suspendedItemId: string,
    extraHttpRequestParams?: any
  ): Observable<SuspendedItemResponse>;

  /**
   * Retrieves the suspended item using the passed in ID from the Suspended Items DB and creates the new adm record and updates the remaining records in the Jenzabar CX database
   *
   * @param suspendedItemId ID of the suspended item to process as an update in Jenzabar CX
   */
  workdayHcm004PutApiWorkdayHcm004(
    suspendedItemId: string,
    extraHttpRequestParams?: any
  ): Observable<SuspendedItemResponse>;

  /**
   * Retrieves the suspended item using the passed in ID from the Suspended Items DB and creates the new adm record and updates the remaining records in the Jenzabar CX database
   *
   * @param suspendedItemId ID of the suspended item to process as an update in Jenzabar CX
   */
  workdayHcm004PutSuspendedItem(
    suspendedItemId: string,
    extraHttpRequestParams?: any
  ): Observable<SuspendedItemResponse>;
}
