/**
 * UF.DataAccess.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { FullSyncResponse } from '../model/fullSyncResponse';
import { LogDetailResponse } from '../model/logDetailResponse';

import { Configuration } from '../configuration';

export interface WorkdayFin108ServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   * Initiates the creation of the Journal Connector CSV file for the FIN.INT108 integration
   *
   */
  workdayFin108FinInt108Begin(extraHttpRequestParams?: any): Observable<FullSyncResponse>;

  /**
   * Displays the import log for the given date
   *
   * @param exportDate
   */
  workdayFin108GetApiWorkdayFin108(exportDate: string, extraHttpRequestParams?: any): Observable<LogDetailResponse>;

  /**
   * Displays the import log for the given date
   *
   * @param exportDate
   */
  workdayFin108GetSyncLog(exportDate: string, extraHttpRequestParams?: any): Observable<LogDetailResponse>;

  /**
   * Gets a distinct list of dates that can be used for import log information
   *
   */
  workdayFin108GetSyncLogDates(extraHttpRequestParams?: any): Observable<LogDetailResponse>;
}
