/**
 * UF.DataAccess.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { FullSyncResponse } from '../model/fullSyncResponse';
import { LogDetailResponse } from '../model/logDetailResponse';
import { StudentEligibilityResponse } from '../model/studentEligibilityResponse';
import { WorkStudyResponse } from '../model/workStudyResponse';

import { Configuration } from '../configuration';

export interface WorkdayHcm008ServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   * Displays the import log for the given date
   *
   * @param exportDate Date the export from Workday HCM.INT008 Data Radius and import into Jenzabar CX occured.
   */
  workdayHcm008GetApiWorkdayHcm008(exportDate: string, extraHttpRequestParams?: any): Observable<LogDetailResponse>;

  /**
   * Gets Student Eligibility data
   *
   */
  workdayHcm008GetSeStudents(extraHttpRequestParams?: any): Observable<StudentEligibilityResponse>;

  /**
   * Displays the import log for the given date
   *
   * @param exportDate Date the export from Workday HCM.INT008 Data Radius and import into Jenzabar CX occured.
   */
  workdayHcm008GetSyncLog(exportDate: string, extraHttpRequestParams?: any): Observable<LogDetailResponse>;

  /**
   * Gets a distinct list of dates that can be used for import log information
   *
   */
  workdayHcm008GetSyncLogDates(extraHttpRequestParams?: any): Observable<LogDetailResponse>;

  /**
   * Gets Work Study Student data
   *
   */
  workdayHcm008GetWsStudents(extraHttpRequestParams?: any): Observable<WorkStudyResponse>;

  /**
   * Initiates the creation of the Workstudy Award data CSV file for the HCM.INT008 integration
   *
   */
  workdayHcm008HcmInt008Begin(extraHttpRequestParams?: any): Observable<FullSyncResponse>;
}
