/**
 * UF.DataAccess.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { FullSyncResponse } from '../model/fullSyncResponse';
import { LogDetailResponse } from '../model/logDetailResponse';

import { Configuration } from '../configuration';

export interface WorkdayHcm023ServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   * Displays the import log for the given date
   *
   * @param exportDate Date the export from Workday HCM.INT023 Data Radius and import into Jenzabar CX occured.
   */
  workdayHcm023GetSyncLog(exportDate: string, extraHttpRequestParams?: any): Observable<LogDetailResponse>;

  /**
   * Gets a distinct list of dates that can be used for import log information
   *
   */
  workdayHcm023GetSyncLogDates(extraHttpRequestParams?: any): Observable<LogDetailResponse>;

  /**
   * Displays the import translation errors log for the given date
   *
   * @param exportDate Date the export from Workday HCM.INT004 Demographics Data Radius and import into Jenzabar CX occured.
   */
  workdayHcm023GetSyncTranslationLog(exportDate: string, extraHttpRequestParams?: any): Observable<LogDetailResponse>;

  /**
   * Initiates the creation of the Workstudy Award data CSV file for the HCM.INT023 integration
   *
   */
  workdayHcm023HcmInt023Begin(extraHttpRequestParams?: any): Observable<FullSyncResponse>;
}
