/**
 * UF.DataAccess.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { CcpStudentsResponse } from '../model/ccpStudentsResponse';
import { LogDetailResponse } from '../model/logDetailResponse';

import { Configuration } from '../configuration';

export interface WorkdayCcpStudentsServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   * Displays the import log for the given date
   *
   * @param exportDate Date the export from Workday HCM.INT008 Data Radius and import into Jenzabar CX occured.
   */
  workdayCcpStudentsGetApiWorkdayCcpStudents(
    exportDate: string,
    extraHttpRequestParams?: any
  ): Observable<LogDetailResponse>;

  /**
   * Gets Student Eligibility data
   *
   */
  workdayCcpStudentsGetCcpStudents(extraHttpRequestParams?: any): Observable<CcpStudentsResponse>;

  /**
   * Displays the import log for the given date
   *
   * @param exportDate Date the export from Workday HCM.INT008 Data Radius and import into Jenzabar CX occured.
   */
  workdayCcpStudentsGetSyncLog(exportDate: string, extraHttpRequestParams?: any): Observable<LogDetailResponse>;

  /**
   * Gets a distinct list of dates that can be used for import log information
   *
   */
  workdayCcpStudentsGetSyncLogDates(extraHttpRequestParams?: any): Observable<LogDetailResponse>;
}
